"""empty message

Revision ID: ed8d4e560676
Revises: 
Create Date: 2024-07-28 23:55:31.132230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8d4e560676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_data',
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('cur_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('room_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_data')
    # ### end Alembic commands ###
